FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y git sudo

RUN git clone https://github.com/PDP-10/its.git

WORKDIR its
RUN sh -ex ./build/dependencies.sh install_linux EMULATOR=simh
RUN make EMULATOR=simh

ENTRYPOINT ["./start"]