FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y git

RUN git clone https://github.com/PDP-10/its.git

WORKDIR its
RUN .build/dependencies.sh install_linux EMULATOR=klh10
RUN make EMULATOR=klh10

ENTRYPOINT ["./start"]