FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y git sudo

RUN git clone https://github.com/PDP-10/its.git

WORKDIR its
RUN EMULATOR=pdp10-ka sh -ex ./build/dependencies.sh install_linux
RUN make EMULATOR=pdp10-ka

ENTRYPOINT ["./start"]