FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y git sudo

RUN git clone https://github.com/PDP-10/its.git

WORKDIR its
RUN sh -ex ./build/dependencies.sh install_linux EMULATOR=klh10
RUN make EMULATOR=klh10

ENTRYPOINT ["./start"]