name: ITS simh
run-name: Build ITS under simh
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker build . --file Dockerfile-simh --tag ghcr.io/mfgamallo/its-simh:0.0.2
      - run: docker push ghcr.io/mfgamallo/its-simh:0.0.3
