name: ITS pdp10-ka
run-name: Build ITS under pdp10-ka
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker build . --file Dockerfile-pdp10-ka --tag ghcr.io/mfgamallo/its-pdp10-ka:0.0.2
      - run: docker push ghcr.io/mfgamallo/its-pdp10-ka:0.0.2
